package mybatis.generator.mapper;

import java.util.List;
import mybatis.generator.model.IsMenu;
import mybatis.generator.model.IsMenuExample;
import org.apache.ibatis.annotations.Param;

public interface IsMenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table is_menu
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	long countByExample(IsMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table is_menu
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int deleteByExample(IsMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table is_menu
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int deleteByPrimaryKey(String menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table is_menu
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int insert(IsMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table is_menu
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int insertSelective(IsMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table is_menu
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */List<IsMenu> selectByExample(IsMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table is_menu
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	IsMenu selectByPrimaryKey(String menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table is_menu
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */int updateByExampleSelective(@Param("record") IsMenu record,@Param("example") IsMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table is_menu
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */int updateByExample(@Param("record") IsMenu record,@Param("example") IsMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table is_menu
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int updateByPrimaryKeySelective(IsMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table is_menu
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int updateByPrimaryKey(IsMenu record);
}