package mybatis.generator.mapper;

import java.util.List;
import mybatis.generator.model.SmPrivgrpPriv;
import mybatis.generator.model.SmPrivgrpPrivExample;
import mybatis.generator.model.SmPrivgrpPrivKey;
import org.apache.ibatis.annotations.Param;

public interface SmPrivgrpPrivMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_privgrp_priv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	long countByExample(SmPrivgrpPrivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_privgrp_priv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int deleteByExample(SmPrivgrpPrivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_privgrp_priv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int deleteByPrimaryKey(SmPrivgrpPrivKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_privgrp_priv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int insert(SmPrivgrpPriv record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_privgrp_priv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int insertSelective(SmPrivgrpPriv record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_privgrp_priv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */List<SmPrivgrpPriv> selectByExample(SmPrivgrpPrivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_privgrp_priv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	SmPrivgrpPriv selectByPrimaryKey(SmPrivgrpPrivKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_privgrp_priv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */int updateByExampleSelective(@Param("record") SmPrivgrpPriv record,@Param("example") SmPrivgrpPrivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_privgrp_priv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */int updateByExample(@Param("record") SmPrivgrpPriv record,@Param("example") SmPrivgrpPrivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_privgrp_priv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int updateByPrimaryKeySelective(SmPrivgrpPriv record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_privgrp_priv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int updateByPrimaryKey(SmPrivgrpPriv record);
}