package mybatis.generator.mapper;

import java.util.List;
import mybatis.generator.model.SmUserpriv;
import mybatis.generator.model.SmUserprivExample;
import mybatis.generator.model.SmUserprivKey;
import org.apache.ibatis.annotations.Param;

public interface SmUserprivMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_userpriv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	long countByExample(SmUserprivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_userpriv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int deleteByExample(SmUserprivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_userpriv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int deleteByPrimaryKey(SmUserprivKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_userpriv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int insert(SmUserpriv record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_userpriv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int insertSelective(SmUserpriv record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_userpriv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */List<SmUserpriv> selectByExample(SmUserprivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_userpriv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	SmUserpriv selectByPrimaryKey(SmUserprivKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_userpriv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */int updateByExampleSelective(@Param("record") SmUserpriv record,@Param("example") SmUserprivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_userpriv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */int updateByExample(@Param("record") SmUserpriv record,@Param("example") SmUserprivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_userpriv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int updateByPrimaryKeySelective(SmUserpriv record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_userpriv
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	int updateByPrimaryKey(SmUserpriv record);
}