package mybatis.generator.model;

public class IsMenu {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column is_menu.MENU_ID
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private String menuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column is_menu.MENU_NAME
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private String menuName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column is_menu.UP_MENU_ID
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private String upMenuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column is_menu.PROGRM_URL
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private String progrmUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column is_menu.SORT_ORDER
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private Integer sortOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column is_menu.USE_YN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private String useYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column is_menu.UPDT_DT
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private String updtDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column is_menu.UPDUSR_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private Integer updusrSn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column is_menu.MENU_ID
	 * @return  the value of is_menu.MENU_ID
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public String getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column is_menu.MENU_ID
	 * @param menuId  the value for is_menu.MENU_ID
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column is_menu.MENU_NAME
	 * @return  the value of is_menu.MENU_NAME
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public String getMenuName() {
		return menuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column is_menu.MENU_NAME
	 * @param menuName  the value for is_menu.MENU_NAME
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column is_menu.UP_MENU_ID
	 * @return  the value of is_menu.UP_MENU_ID
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public String getUpMenuId() {
		return upMenuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column is_menu.UP_MENU_ID
	 * @param upMenuId  the value for is_menu.UP_MENU_ID
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setUpMenuId(String upMenuId) {
		this.upMenuId = upMenuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column is_menu.PROGRM_URL
	 * @return  the value of is_menu.PROGRM_URL
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public String getProgrmUrl() {
		return progrmUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column is_menu.PROGRM_URL
	 * @param progrmUrl  the value for is_menu.PROGRM_URL
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setProgrmUrl(String progrmUrl) {
		this.progrmUrl = progrmUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column is_menu.SORT_ORDER
	 * @return  the value of is_menu.SORT_ORDER
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public Integer getSortOrder() {
		return sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column is_menu.SORT_ORDER
	 * @param sortOrder  the value for is_menu.SORT_ORDER
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column is_menu.USE_YN
	 * @return  the value of is_menu.USE_YN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public String getUseYn() {
		return useYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column is_menu.USE_YN
	 * @param useYn  the value for is_menu.USE_YN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setUseYn(String useYn) {
		this.useYn = useYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column is_menu.UPDT_DT
	 * @return  the value of is_menu.UPDT_DT
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public String getUpdtDt() {
		return updtDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column is_menu.UPDT_DT
	 * @param updtDt  the value for is_menu.UPDT_DT
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setUpdtDt(String updtDt) {
		this.updtDt = updtDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column is_menu.UPDUSR_SN
	 * @return  the value of is_menu.UPDUSR_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public Integer getUpdusrSn() {
		return updusrSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column is_menu.UPDUSR_SN
	 * @param updusrSn  the value for is_menu.UPDUSR_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setUpdusrSn(Integer updusrSn) {
		this.updusrSn = updusrSn;
	}
}