package mybatis.generator.model;

public class SmPrivgrpPrivKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_privgrp_priv.PRIVGRP_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private Integer privgrpSn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_privgrp_priv.PRIV_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private Integer privSn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_privgrp_priv.PRIVGRP_SN
	 * @return  the value of sm_privgrp_priv.PRIVGRP_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public Integer getPrivgrpSn() {
		return privgrpSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_privgrp_priv.PRIVGRP_SN
	 * @param privgrpSn  the value for sm_privgrp_priv.PRIVGRP_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setPrivgrpSn(Integer privgrpSn) {
		this.privgrpSn = privgrpSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_privgrp_priv.PRIV_SN
	 * @return  the value of sm_privgrp_priv.PRIV_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public Integer getPrivSn() {
		return privSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_privgrp_priv.PRIV_SN
	 * @param privSn  the value for sm_privgrp_priv.PRIV_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setPrivSn(Integer privSn) {
		this.privSn = privSn;
	}
}