package mybatis.generator.model;

public class SmPrivgrp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_privgrp.PRIVGRP_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private Integer privgrpSn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_privgrp.PRIVGRP_NAME
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private String privgrpName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_privgrp.PRIVGRP_DESC
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private String privgrpDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_privgrp.PRIORT
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private Integer priort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_privgrp.USE_YN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private String useYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_privgrp.UPDT_DT
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private String updtDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_privgrp.UPDUSR_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private Integer updusrSn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_privgrp.PRIVGRP_SN
	 * @return  the value of sm_privgrp.PRIVGRP_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public Integer getPrivgrpSn() {
		return privgrpSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_privgrp.PRIVGRP_SN
	 * @param privgrpSn  the value for sm_privgrp.PRIVGRP_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setPrivgrpSn(Integer privgrpSn) {
		this.privgrpSn = privgrpSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_privgrp.PRIVGRP_NAME
	 * @return  the value of sm_privgrp.PRIVGRP_NAME
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public String getPrivgrpName() {
		return privgrpName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_privgrp.PRIVGRP_NAME
	 * @param privgrpName  the value for sm_privgrp.PRIVGRP_NAME
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setPrivgrpName(String privgrpName) {
		this.privgrpName = privgrpName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_privgrp.PRIVGRP_DESC
	 * @return  the value of sm_privgrp.PRIVGRP_DESC
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public String getPrivgrpDesc() {
		return privgrpDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_privgrp.PRIVGRP_DESC
	 * @param privgrpDesc  the value for sm_privgrp.PRIVGRP_DESC
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setPrivgrpDesc(String privgrpDesc) {
		this.privgrpDesc = privgrpDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_privgrp.PRIORT
	 * @return  the value of sm_privgrp.PRIORT
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public Integer getPriort() {
		return priort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_privgrp.PRIORT
	 * @param priort  the value for sm_privgrp.PRIORT
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setPriort(Integer priort) {
		this.priort = priort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_privgrp.USE_YN
	 * @return  the value of sm_privgrp.USE_YN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public String getUseYn() {
		return useYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_privgrp.USE_YN
	 * @param useYn  the value for sm_privgrp.USE_YN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setUseYn(String useYn) {
		this.useYn = useYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_privgrp.UPDT_DT
	 * @return  the value of sm_privgrp.UPDT_DT
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public String getUpdtDt() {
		return updtDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_privgrp.UPDT_DT
	 * @param updtDt  the value for sm_privgrp.UPDT_DT
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setUpdtDt(String updtDt) {
		this.updtDt = updtDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_privgrp.UPDUSR_SN
	 * @return  the value of sm_privgrp.UPDUSR_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public Integer getUpdusrSn() {
		return updusrSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_privgrp.UPDUSR_SN
	 * @param updusrSn  the value for sm_privgrp.UPDUSR_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setUpdusrSn(Integer updusrSn) {
		this.updusrSn = updusrSn;
	}
}