package mybatis.generator.model;

public class SmPrivgrpPriv extends SmPrivgrpPrivKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_privgrp_priv.MENU_ID
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private String menuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_privgrp_priv.UPDT_DT
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private String updtDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_privgrp_priv.UPDUSR_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private Integer updusrSn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_privgrp_priv.INQIRE_YN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private String inqireYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_privgrp_priv.WRITE_YN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private String writeYn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_privgrp_priv.MENU_ID
	 * @return  the value of sm_privgrp_priv.MENU_ID
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public String getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_privgrp_priv.MENU_ID
	 * @param menuId  the value for sm_privgrp_priv.MENU_ID
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_privgrp_priv.UPDT_DT
	 * @return  the value of sm_privgrp_priv.UPDT_DT
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public String getUpdtDt() {
		return updtDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_privgrp_priv.UPDT_DT
	 * @param updtDt  the value for sm_privgrp_priv.UPDT_DT
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setUpdtDt(String updtDt) {
		this.updtDt = updtDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_privgrp_priv.UPDUSR_SN
	 * @return  the value of sm_privgrp_priv.UPDUSR_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public Integer getUpdusrSn() {
		return updusrSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_privgrp_priv.UPDUSR_SN
	 * @param updusrSn  the value for sm_privgrp_priv.UPDUSR_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setUpdusrSn(Integer updusrSn) {
		this.updusrSn = updusrSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_privgrp_priv.INQIRE_YN
	 * @return  the value of sm_privgrp_priv.INQIRE_YN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public String getInqireYn() {
		return inqireYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_privgrp_priv.INQIRE_YN
	 * @param inqireYn  the value for sm_privgrp_priv.INQIRE_YN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setInqireYn(String inqireYn) {
		this.inqireYn = inqireYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_privgrp_priv.WRITE_YN
	 * @return  the value of sm_privgrp_priv.WRITE_YN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public String getWriteYn() {
		return writeYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_privgrp_priv.WRITE_YN
	 * @param writeYn  the value for sm_privgrp_priv.WRITE_YN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setWriteYn(String writeYn) {
		this.writeYn = writeYn;
	}
}