package mybatis.generator.model;

public class SmUserpriv extends SmUserprivKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_userpriv.UPDT_DT
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private String updtDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_userpriv.UPDUSR_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private Integer updusrSn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_userpriv.PRIV_REQUST_STTUS_CD
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private String privRequstSttusCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_userpriv.PRIV_REQUST_RETURN_RESN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private String privRequstReturnResn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_userpriv.UPDT_DT
	 * @return  the value of sm_userpriv.UPDT_DT
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public String getUpdtDt() {
		return updtDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_userpriv.UPDT_DT
	 * @param updtDt  the value for sm_userpriv.UPDT_DT
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setUpdtDt(String updtDt) {
		this.updtDt = updtDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_userpriv.UPDUSR_SN
	 * @return  the value of sm_userpriv.UPDUSR_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public Integer getUpdusrSn() {
		return updusrSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_userpriv.UPDUSR_SN
	 * @param updusrSn  the value for sm_userpriv.UPDUSR_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setUpdusrSn(Integer updusrSn) {
		this.updusrSn = updusrSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_userpriv.PRIV_REQUST_STTUS_CD
	 * @return  the value of sm_userpriv.PRIV_REQUST_STTUS_CD
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public String getPrivRequstSttusCd() {
		return privRequstSttusCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_userpriv.PRIV_REQUST_STTUS_CD
	 * @param privRequstSttusCd  the value for sm_userpriv.PRIV_REQUST_STTUS_CD
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setPrivRequstSttusCd(String privRequstSttusCd) {
		this.privRequstSttusCd = privRequstSttusCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_userpriv.PRIV_REQUST_RETURN_RESN
	 * @return  the value of sm_userpriv.PRIV_REQUST_RETURN_RESN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public String getPrivRequstReturnResn() {
		return privRequstReturnResn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_userpriv.PRIV_REQUST_RETURN_RESN
	 * @param privRequstReturnResn  the value for sm_userpriv.PRIV_REQUST_RETURN_RESN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setPrivRequstReturnResn(String privRequstReturnResn) {
		this.privRequstReturnResn = privRequstReturnResn;
	}
}