package mybatis.generator.model;

public class SmUserprivKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_userpriv.USER_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private Integer userSn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_userpriv.PRIVGRP_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	private Integer privgrpSn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_userpriv.USER_SN
	 * @return  the value of sm_userpriv.USER_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public Integer getUserSn() {
		return userSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_userpriv.USER_SN
	 * @param userSn  the value for sm_userpriv.USER_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setUserSn(Integer userSn) {
		this.userSn = userSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_userpriv.PRIVGRP_SN
	 * @return  the value of sm_userpriv.PRIVGRP_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public Integer getPrivgrpSn() {
		return privgrpSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_userpriv.PRIVGRP_SN
	 * @param privgrpSn  the value for sm_userpriv.PRIVGRP_SN
	 * @mbg.generated  Tue Nov 28 17:51:43 KST 2017
	 */
	public void setPrivgrpSn(Integer privgrpSn) {
		this.privgrpSn = privgrpSn;
	}
}